<!DOCTYPE library [
<!ELEMENT library (books,members,staff,publisher)>
<!ELEMENT books (book1,book2)>
<!ELEMENT book1 (title,author,price,isbn,year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ATTLIST book1 bookId CDATA #REQUIRED>
<!ELEMENT book2 (title,author,price,isbn,year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ATTLIST book2 bookId CDATA #REQUIRED>
<!ELEMENT members (member1,member2)>
<!ELEMENT member1 (name,phone,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST member1 memberId CDATA #REQUIRED>
<!ELEMENT member2 (name,phone,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST member2 memberId CDATA #REQUIRED>
<!ELEMENT staff1 (name,phone,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST staff1 staffId CDATA #REQUIRED>
<!ELEMENT staff2 (name,phone,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST staff2 staffId CDATA #REQUIRED>
<!ELEMENT publisher (name,phone,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ATTLIST publisher publisherId CDATA #REQUIRED>
]>
<library>
    <books>
	<book1 bookId="1">
	    <title> Web Development Technology </title>
	    <author> Dhana </author>
	    <price> 600 </price>
	    <isbn> 895612783123 </isbn>
            <year> 2023 </year>
        </book1>
	<book2 bookId="2">
	    <title> Artificial Intelligence </title>
	    <author> Sweetha </author>
	    <price> 550 </price>
	    <isbn> 9546871236483 </isbn>
            <year> 2022 </year>
        </book2>
    </books>
    <members>
	<member1 memberId="101">
	    <name> Raju </name>
	    <phone> 9867451231 </phone>
	    <address> Hyderabad </address>
	</member1>
	<member2 memberId="102">
	    <name> Fateh </name>
	    <phone> 9867984562 </phone>
	    <address> Punjab </address>
	</member2>
    </members>
    <staff>
	<staff1 staffId="201">
	    <name> Megha </name>
	    <phone> 9867654831 </phone>
	    <address> Bangalore </address>
	</staff1>
	<staff2 staffId="202">
	    <name> Pratha </name>
	    <phone> 9845622831 </phone>
	    <address> Mumbai </address>
	</staff2>
    </staff>
    <publisher publisherId="603">
	<name> Midhuna </name>
	<phone> 3256622831 </phone>
	<address> Chennai </address>
    </publisher>
</library>